<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PE-HO-012" failures="1" tests="3" name="Default test" time="7.47" errors="0" timestamp="2022-09-30T08:34:36 COT">
  <testcase classname="run.Run" name="crearCuenta" time="0.0">
    <skipped/>
  </testcase> <!-- crearCuenta -->
  <testcase classname="run.Run" name="alertsTools" time="4.917">
    <failure type="com.itextpdf.text.DocumentException" message="The document is not open yet; you can only add Meta information.">
      <![CDATA[com.itextpdf.text.DocumentException: The document is not open yet; you can only add Meta information.
at com.itextpdf.text.Document.add(Document.java:270)
at Utilidades.GenerarReportePdf.crearBody(GenerarReportePdf.java:116)
at claseBase.ClaseBase.captureScreen(ClaseBase.java:167)
at claseBase.ClaseBase.clickTools(ClaseBase.java:63)
at pagesObject.PageOBjectHomeTools.buttonAlert(PageOBjectHomeTools.java:33)
at run.Run.alertsTools(Run.java:197)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- alertsTools -->
  <testcase classname="run.Run" name="alertsTools" time="0.0">
    <skipped/>
  </testcase> <!-- alertsTools -->
</testsuite> <!-- Default test -->
